baseURL = "https://codeweek.c3re.de"
languageCode = "de-de"
title = "CodeWeek @c3RE"
theme = "hugo-split-theme"
paginate = 5
twitterHandle = "c3_re"
copyright = "&copy;2019 c3RE"
DefaultContentLanguage = "de"


[params]
    author = "c3re.de"
    description = "Chaostreff Recklinghausen"
    avatar = "images/logo.png" 
[params.visual.image]
      enable = true
      file = "images/2019Plakat.png"
      position = "fixed fixed"


[[params.links]]
    [params.links.list1]
      heading = "Weitere Links"

      [[params.links.list1.link]]
        text = "Linkliste"
        url = "linklist"

      [[params.links.list1.link]]
        text = "Teileliste"
        url = "partlist"

      [[params.links.list1.link]]
        text = "Impressum"
        url = "https://www.c3re.de/impressum/"